In [114]:
 # here we are imprting the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import math
import os
from PIL import Image
from sklearn import neighbors
from sklearn import metrics



In [115]:
def rgbDetailsInImage(image):
    
    totalRGBValue = np.array(image).mean(axis=(0,1))
    R = totalRGBValue[0]
    G = totalRGBValue[1]
    B = totalRGBValue[2]
    
    Sum = totalRGBValue[0] + totalRGBValue[1] + totalRGBValue[2]
    
    percentR = totalRGBValue[0]/Sum                                       
    percentG = totalRGBValue[1]/Sum
    percentB = totalRGBValue[2]/Sum
    
    return percentR,percentG, percentB

In [116]:


#Loading the Training data from the given 
path="C:\\Users\\ajay9\\Downloads\\Bruned images\\Bruned images\\Training_data"
imagefiles=os.listdir(path)
print("----------------------------------------------------------------------------------------------")
#since the given folder contains DS_Store it will be removed as below command
imagefiles.remove('.DS_Store')
for i in imagefiles:
    print(i)
print(len(imagefiles))

----------------------------------------------------------------------------------------------
img1.jpg
img10.jpg
img11.jpg
img12.jpg
img13.jpg
img14.jpg
img15.jpg
img16.jpg
img17.jpg
img18.jpg
img19.jpg
img2.jpg
img20.jpg
img21.jpg
img22.jpg
img23.jpg
img24.jpg
img25.jpg
img26.jpg
img27.jpg
img28.jpg
img29.jpg
img3.jpg
img30.jpg
img31.jpg
img32.jpg
img33.jpg
img34.jpg
img35.jpg
img36.jpg
img37.jpg
img38.jpg
img39.jpg
img4.jpg
img40.jpg
img41.jpg
img42.jpg
img43.jpg
img44.jpg
img45.jpg
img46.jpg
img47.jpg
img48.jpg
img49.jpg
img5.jpg
img50.jpg
img51.jpg
img52.jpg
img53.jpg
img54.jpg
img55.jpg
img56.jpg
img57.jpg
img58.jpg
img59.jpg
img6.jpg
img60.jpg
img7.jpg
img8.jpg
img9.jpg
nimg1.jpeg
nimg2.jpeg
nimg3.jpeg
nimg4.jpeg
nimg5.jpeg
nimg6.jpeg
66


In [117]:

#assigning the Labels for the Training data
TrainingLabels = ['burn' if image.startswith('i') else 'notburn' for image in imagefiles ]
#Checking the TrainingLabels
print(TrainingLabels)
# checking whether the total labels are assigned or not.
print(len(TrainingLabels))


['burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'notburn', 'notburn', 'notburn', 'notburn', 'notburn', 'notburn']
66


In [118]:
#Since the we just loaded the images now we are going to extract the RGBvalues of the each image that we loaded
trainingset = [] # after extracting the RGB value of each image we are going to append the each RGB value into this Training set
for i in imagefiles:
    imagepath = 'C:\\Users\\ajay9\\Downloads\\Bruned images\\Bruned images\\Training_data\\' + i
    
    img = Image.open(imagepath)
   
    trainingset.append(rgbDetailsInImage(img)) #using the function defined before
    

print("The RGB values of the each image that we loaded as training data")   
print("------------------------------------------------------------------------------------------------------------")
RGB_TrainingArray= np.array(trainingset)
print(RGB_TrainingArray)

The RGB values of the each image that we loaded as training data
------------------------------------------------------------------------------------------------------------
[[0.42520099 0.30435003 0.27044897]
 [0.38874152 0.32624389 0.28501459]
 [0.36840558 0.32176806 0.30982635]
 [0.36840558 0.32176806 0.30982635]
 [0.38970389 0.30817766 0.30211845]
 [0.46181488 0.27848414 0.25970098]
 [0.41428982 0.31884883 0.26686135]
 [0.37784529 0.31121264 0.31094207]
 [0.35305823 0.33170995 0.31523182]
 [0.36716732 0.30927295 0.32355973]
 [0.37160438 0.30080512 0.32759051]
 [0.4596631  0.32764069 0.21269622]
 [0.3637359  0.3271627  0.3091014 ]
 [0.3828321  0.32307611 0.2940918 ]
 [0.37367447 0.32703539 0.29929014]
 [0.34920394 0.32151774 0.32927831]
 [0.41314529 0.31894789 0.26790683]
 [0.36884861 0.32676576 0.30438562]
 [0.36373807 0.31084273 0.32541919]
 [0.44056839 0.28948625 0.26994535]
 [0.46027413 0.32716861 0.21255725]
 [0.45812826 0.31058049 0.23129124]
 [0.33836867 0.34130102 0.32033032

In [119]:
k1 = neighbors.KNeighborsClassifier(1,weights='distance') # initiating the KNN classifier with n-neighbors as 1

In [120]:
k1.fit(RGB_TrainingArray,TrainingLabels) # Now we are fit the Images values to the TrianingLabels

KNeighborsClassifier(n_neighbors=1, weights='distance')

In [121]:
import random

Testimage  = ['img64.jpg', 'img65.jpg', 'nimg7.jpeg']
TestSet_Images = []

TestImagesPath="C:\\Users\\ajay9\\Downloads\\Bruned images\\Bruned images\\Testing_data"

imagefiles_test=os.listdir(TestImagesPath)

#Testset= random.sample(imagefiles_test, 3) # Selecting the 3 random images to test the algorithm
for i in Testimage:
    imagepath = 'C:\\Users\\ajay9\\Downloads\\Bruned images\\Bruned images\\Testing_data\\' + i 
    
    
    img = Image.open(imagepath)
    
    TestSet_Images.append(rgbDetailsInImage(img)) #using the function defined before
    
print(Testimage)


for i in TestSet_Images:
    print(i)

print(TestSet_Images)

TestLabels = ['burn' if image.startswith('i') else 'notburn' for image in Testimage] # Setting the Labels for the truth values

print(TestLabels)


['img64.jpg', 'img65.jpg', 'nimg7.jpeg']
(0.3866068411201154, 0.32173062843164274, 0.2916625304482418)
(0.3855221186650065, 0.32065001658265924, 0.29382786475233436)
(0.34557617590194173, 0.3305853644087891, 0.3238384596892691)
[(0.3866068411201154, 0.32173062843164274, 0.2916625304482418), (0.3855221186650065, 0.32065001658265924, 0.29382786475233436), (0.34557617590194173, 0.3305853644087891, 0.3238384596892691)]
['burn', 'burn', 'notburn']


In [122]:
#PercentRed values from Test set
PercentRed = [x for x, y,z in TestSet_Images]

PercentRedArray = np.array(PercentRed)

PercentGreen = [y for x, y,z in TestSet_Images]

PercentGreenArray = np.array(PercentGreen)

PercentBlue = [z for x, y,z in TestSet_Images]

PercentBlueArray = np.array(PercentBlue)
    

RGB_TestArray = np.column_stack((PercentRedArray,PercentGreenArray,PercentBlueArray))

print("Numpy Array with the TestSet values of PercentGreen and PercentBlue of the Test images")
print("---------------------------------------------")
print(RGB_TestArray)

Numpy Array with the TestSet values of PercentGreen and PercentBlue of the Test images
---------------------------------------------
[[0.38660684 0.32173063 0.29166253]
 [0.38552212 0.32065002 0.29382786]
 [0.34557618 0.33058536 0.32383846]]


In [123]:
RGB_TestArray= np.array(TestSet_Images) # Assigning the values into the array
print(GB_TestArray)

[[0.38660684 0.32173063 0.29166253]
 [0.38552212 0.32065002 0.29382786]
 [0.34557618 0.33058536 0.32383846]]


In [124]:
k1_pred = k1.predict(RGB_TestArray)# we are predicting the algo using the test values

print("Predicted Values of Three Images:")
print(k1_pred)

Predicted Values of Three Images:
['burn' 'burn' 'notburn']


In [125]:
from sklearn.metrics import accuracy_score, recall_score, average_precision_score, confusion_matrix, precision_score
confusion_matrix(y_true=TestLabels, y_pred=k1_pred)#implement the confusion matrix

array([[2, 0],
       [0, 1]], dtype=int64)

In [126]:
accuracy_k1 = accuracy_score(TestLabels,k1_pred)
print('Accuracy for k=1')
print(accuracy_k1*100 ,"%") # Here we are checking the accuracy about our prediction

Accuracy for k=1
100.0 %


In [127]:
# Now we are going to initiate the Input2-> Training the KNN-classifier with only 60% of the Training data
# Here we can use 2 ways on with the library from sklearn.model_selection import train_test_split or by using the random choice 
# Here we have the test size for example if the test_size= 0.5 then the training data will be used 50 % only.Here I am going to use the same thing


In [128]:
def rgbDetailsInImage_Input2(image):
    
    totalRGBValue_Input2 = np.array(image).mean(axis=(0,1))
    R = totalRGBValue_Input2[0]
    G = totalRGBValue_Input2[1]
    B = totalRGBValue_Input2[2]
    
    Sum_Input2 = totalRGBValue_Input2[0] + totalRGBValue_Input2[1] + totalRGBValue_Input2[2]
    
    percentR_Input2 = totalRGBValue_Input2[0]/Sum_Input2                                       
    percentG_Input2 = totalRGBValue_Input2[1]/Sum_Input2
    percentB_Input2 = totalRGBValue_Input2[2]/Sum_Input2
    
    return percentR_Input2,percentG_Input2, percentB_Input2

In [129]:
#Loading the Training data from the given 
path="C:\\Users\\ajay9\\Downloads\\Bruned images\\Bruned images\\Training_data"
imagefiles_Input2=os.listdir(path)
print("----------------------------------------------------------------------------------------------")
#since the given folder contains DS_Store it will be removed as below command
imagefiles_Input2.remove('.DS_Store')
for i in imagefiles_Input2:
    print(i)
print(len(imagefiles_Input2))

----------------------------------------------------------------------------------------------
img1.jpg
img10.jpg
img11.jpg
img12.jpg
img13.jpg
img14.jpg
img15.jpg
img16.jpg
img17.jpg
img18.jpg
img19.jpg
img2.jpg
img20.jpg
img21.jpg
img22.jpg
img23.jpg
img24.jpg
img25.jpg
img26.jpg
img27.jpg
img28.jpg
img29.jpg
img3.jpg
img30.jpg
img31.jpg
img32.jpg
img33.jpg
img34.jpg
img35.jpg
img36.jpg
img37.jpg
img38.jpg
img39.jpg
img4.jpg
img40.jpg
img41.jpg
img42.jpg
img43.jpg
img44.jpg
img45.jpg
img46.jpg
img47.jpg
img48.jpg
img49.jpg
img5.jpg
img50.jpg
img51.jpg
img52.jpg
img53.jpg
img54.jpg
img55.jpg
img56.jpg
img57.jpg
img58.jpg
img59.jpg
img6.jpg
img60.jpg
img7.jpg
img8.jpg
img9.jpg
nimg1.jpeg
nimg2.jpeg
nimg3.jpeg
nimg4.jpeg
nimg5.jpeg
nimg6.jpeg
66


In [130]:
#assigning the Labels for the Training data
TrainingLabels_input2 = ['burn' if image.startswith('i') else 'notburn' for image in imagefiles_Input2 ]
#Checking the TrainingLabels
print(TrainingLabels_input2)
# checking whether the total labels are assigned or not.
print(len(TrainingLabels_input2))

['burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'burn', 'notburn', 'notburn', 'notburn', 'notburn', 'notburn', 'notburn']
66


In [131]:
from sklearn.model_selection import train_test_split
imagefiles_Input2_new,_,TrainingLabels_input2_new,_= train_test_split(imagefiles_Input2,TrainingLabels_input2, test_size=0.4, random_state=2)


In [132]:
Input2_trainingset = [] 
for i in imagefiles_Input2_new:
    imagepath = 'C:\\Users\\ajay9\\Downloads\\Bruned images\\Bruned images\\Training_data\\' + i
    
    img = Image.open(imagepath)
    Input2_trainingset.append(rgbDetailsInImage_Input2(img)) #using the function defined before
    

print("RGB % of the Input2 Training data")   
print("------------------------------------------------------------------------------------------------------------")

Input2_TrainingArray=np.array(Input2_trainingset)
print(Input2_TrainingArray)
print(len(Input2_TrainingArray))

RGB % of the Input2 Training data
------------------------------------------------------------------------------------------------------------
[[0.37367447 0.32703539 0.29929014]
 [0.36844373 0.32166977 0.30988649]
 [0.41314529 0.31894789 0.26790683]
 [0.36840558 0.32176806 0.30982635]
 [0.46077306 0.27969531 0.25953163]
 [0.44056839 0.28948625 0.26994535]
 [0.42022414 0.31422384 0.26555202]
 [0.41428982 0.31884883 0.26686135]
 [0.39362075 0.29588284 0.31049641]
 [0.54702969 0.24291365 0.21005666]
 [0.46181488 0.27848414 0.25970098]
 [0.42160342 0.31635799 0.26203858]
 [0.37804846 0.31162832 0.31032322]
 [0.39327223 0.32461819 0.28210958]
 [0.3487433  0.32436706 0.32688964]
 [0.38970389 0.30817766 0.30211845]
 [0.46077306 0.27969531 0.25953163]
 [0.36840558 0.32176806 0.30982635]
 [0.43969001 0.28761356 0.27269644]
 [0.43043536 0.29758617 0.27197848]
 [0.46027413 0.32716861 0.21255725]
 [0.4856299  0.30391649 0.21045361]
 [0.39143016 0.31267214 0.2958977 ]
 [0.39788256 0.31809494 0.284

In [133]:
k1_Input2 = neighbors.KNeighborsClassifier(1,weights='distance')

In [134]:
k1_Input2.fit(Input2_TrainingArray,TrainingLabels_input2_new)

KNeighborsClassifier(n_neighbors=1, weights='distance')

In [135]:
import random

Testimage_input2  = ['img64.jpg', 'img65.jpg', 'nimg7.jpeg']
TestSet_Images_Input2 = []



for i in Testimage_input2:
    imagepath = 'C:\\Users\\ajay9\\Downloads\\Bruned images\\Bruned images\\Testing_data\\' + i 
    
    
    img = Image.open(imagepath)
    
    TestSet_Images_Input2.append(rgbDetailsInImage_Input2(img)) 
    



for i in TestSet_Images_Input2:
    print(i)

TestLabels_input2= ['burn' if image.startswith('i') else 'notburn' for image in Testimage_input2] # Setting the Labels for the truth values

print(TestLabels_input2)

(0.3866068411201154, 0.32173062843164274, 0.2916625304482418)
(0.3855221186650065, 0.32065001658265924, 0.29382786475233436)
(0.34557617590194173, 0.3305853644087891, 0.3238384596892691)
['burn', 'burn', 'notburn']


In [136]:
PercentRed = [x for x, y,z in TestSet_Images_Input2]

PercentRedArray = np.array(PercentRed)

PercentGreen = [y for x, y,z in TestSet_Images_Input2]

PercentGreenArray = np.array(PercentGreen)

PercentBlue = [z for x, y,z in TestSet_Images_Input2]

PercentBlueArray = np.array(PercentBlue)
    

new_RGB_TestArray = np.column_stack((PercentRedArray,PercentGreenArray,PercentBlueArray))

print("Numpy Array with the TestSet values of PercentGreen and PercentBlue of the Test images")
print("---------------------------------------------")
print(new_RGB_TestArray)

Numpy Array with the TestSet values of PercentGreen and PercentBlue of the Test images
---------------------------------------------
[[0.38660684 0.32173063 0.29166253]
 [0.38552212 0.32065002 0.29382786]
 [0.34557618 0.33058536 0.32383846]]


In [137]:
RGB_Test_Array_Input2= np.array(TestSet_Images_Input2)
print(RGB_Test_Array_Input2)

[[0.38660684 0.32173063 0.29166253]
 [0.38552212 0.32065002 0.29382786]
 [0.34557618 0.33058536 0.32383846]]


In [138]:
k1_pred_input2 = k1.predict(RGB_Test_Array_Input2)

print("Predicted Values of Three Images:")
print(k1_pred_input2)

Predicted Values of Three Images:
['burn' 'burn' 'notburn']


In [139]:
confusion_matrix(y_true=TestLabels_input2, y_pred=k1_pred_input2)

array([[2, 0],
       [0, 1]], dtype=int64)

In [140]:
# Conclusion: here we taken the 3 images same for both input1 and input and the confusion matrix for input 1 and input 2 
#generates the same confusion matrix for both the inputs. So we can conclude that input 2 means 60 % training data will be 
#sufficient to predict the data. If we consider different test set for both inputs, then result may varry, but for the given
# we can train the algorithm with 60% of the data.